default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: quest_development
test:
  <<: *default
  database: quest_test
production:
  <<: *default
  database: quest_production
  username:
  password:
