# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cba3b0bcfbb22994549de5a12e64d91c8d88fa05b99c425acf1be3a862b6864939f91a7f5294e9ebfe970a484b32a0b678598ab57d0fb349bfa728251a1edbe

test:
  secret_key_base: 7bf2fe3dafe99616453123890fbdc00729485401f85d5bb9b6ca8203bcf1f3007b917f11619b8f1bb4a2644e10d41017becad5cd4b43fcc30ab5593507a15c8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
